name: slot_booking_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  connectivity_plus: ^7.0.0
  logger: ^2.6.2
  get_it: ^8.2.0
  freezed_annotation: ^3.1.0
  fpdart: ^1.1.1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1
  build_runner: ^2.10.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/
    - assets/images/
    - assets/svgs/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
