name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_requests:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build release APK with obfuscation
        run: flutter build apk --release --obfuscate --split-debug-info=build/debug-info
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk